// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tariffs": {
            "get": {
                "description": "Возвращает список всех тарифов в системе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tariffs"
                ],
                "summary": "Получить все тарифы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Tariff"
                            }
                        }
                    }
                }
            }
        },
        "/tariffs/create": {
            "post": {
                "description": "Добавляет новый тариф в систему",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tariffs"
                ],
                "summary": "Создать тариф",
                "parameters": [
                    {
                        "description": "Данные нового тарифа",
                        "name": "tariff",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TariffRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TariffRequest"
                        }
                    }
                }
            }
        },
        "/tariffs/get": {
            "get": {
                "description": "Возвращает данные тарифа по его идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tariffs"
                ],
                "summary": "Получить тариф по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID тарифа",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tariff"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Tariff": {
            "type": "object",
            "properties": {
                "action_type": {
                    "description": "Тип действия (например, \"Обработка документа\")",
                    "type": "string",
                    "example": "Обработка документа"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "description": "Цена тарифа",
                    "type": "number",
                    "example": 100.5
                },
                "valid_from": {
                    "description": "Начало действия тарифа",
                    "type": "string",
                    "example": "2025-03-14"
                },
                "valid_until": {
                    "description": "Окончание действия тарифа",
                    "type": "string",
                    "example": "2025-12-31"
                }
            }
        },
        "models.TariffRequest": {
            "type": "object",
            "properties": {
                "action_type": {
                    "description": "Тип действия (например, \"Обработка документа\")",
                    "type": "string",
                    "example": "Обработка документа"
                },
                "price": {
                    "description": "Цена тарифа",
                    "type": "number",
                    "example": 10.5
                },
                "valid_from": {
                    "description": "Начало действия тарифа",
                    "type": "string",
                    "example": "2025-03-14"
                },
                "valid_until": {
                    "description": "Окончание действия тарифа",
                    "type": "string",
                    "example": "2025-12-31"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tariff Service API",
	Description:      "API для управления тарифами",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
